local CORE = {}

CORE.SPEED = 30 -- How many ticks in a second.
CORE.SLOWNESS = 1 / CORE.SPEED -- How long a tick should be in seconds.
CORE.FALLOFF_START = 120
CORE.FALLOFF_END = 240
CORE.WIDTH = 384
CORE.HEIGHT = 256

CORE.RECORDED, CORE.UNRECORDED = 1, 2
CORE.INPUTS = {
	FORWARDS = RECORDED,
	STRAFE_LEFT = RECORDED,
	BACKWARDS = RECORDED,
	STRAFE_RIGHT = RECORDED,
	TURN_LEFT = RECORDED,
	TURN_RIGHT= RECORDED,
	USE = RECORDED,
	RUN = RECORDED,
	DUCK = RECORDED,
	SNEAK = RECORDED,
	ACT = RECORDED,
	
	PAUSE = UNRECORDED,
	TAKE_SCREENSHOT = UNRECORDED,
	SCALE_UP = UNRECORDED,
	SCALE_DOWN = UNRECORDED,
	TOGGLE_FULLSCREEN = UNRECORDED,
	TOGGLE_INFO = UNRECORDED
}

return CORE
