local PLAIN = "Alive"

return {
	PLAIN = PLAIN,
	"Not dead!",
	"Almost first!",
	"Spectacular!",
	"Racy!",
	"Dishy!",
	"Rather delightful!",
	"Deterministic!",
	"Chaotic!",
	"Flops down next to you!",
	"Cares about you personally!",
	"Sends your regards to the chef!",
	"British!",
	"Britannian?",
	"Epic!",
	"Epical?",
	"Poetic!",
	"Poetical?",
	"Majestic!",
	"Majestical?",
	"Stygian!",
	"Text-based!",
	"Runs on a Game Boy!",
	"Made in a made-up langauge!",
	"Check out the LIKO-12!",
	"Check in the OKIL+12?",
	"Requires a 256-bit CPU!",
	"Exponential!",
	"Groovy!",
	"Way cool!",
	"Mondo!",
	"Tubular!",
	"Utterly sapient!",
	"Intensity in ten cities!",
	"If it were a president, it'd be Gameoftheyearbraham Lincoln!",
	"Packed full of variables!",
	"Likes the Telecockneys!",
	"Stutters at the worst of times!",
	"Calls feathers bird leaves!",
	"Orang, stop!",
	"Cool and good!",
	"Slaps you with an elastic A!",
	"Shababclampingpongclongsos!",
	"Rips and tears!",
	"Brings you socks!",
	"Eats soap!",
	"Catches hots, not colds!",
	"Is slim-thick!",
	"Is very healthy!",
	"IS NOT FURRY!",
	"Drinks mango juice!",
	"Sleeps upside-down!",
	"Is hyphenated!",
	"Is non-hyphenated!",
	"Oh, the irony!",
	"Ah, the iron!",
	"Takes vitamin D supplements!",
	"Is as white as a sheet!",
	"Shoots, strangles, stabs!",
	"Is very diplomatic!",
	"Hoorah-ho!",
	"Ooga-booga!",
	"Ug-ug!",
	"You, me, baboom!",
	"Sweats profusely!",
	"Married a babushka with an AK-47!",
	"Divorced a babushka without an AK-47!",
	"Olga Elsa Kira Podge Fleminger Thomson!",
	"Thipped and cared... woof!",
	"Good dog!",
	"She has wings now!",
	"Rollo Fleminger Thomson!",
	"Urinated under the desk... meow!",
	"He was still a good boy!",
	"He has wings now!",
	"Has interrobangs!",
	"Hand-crafted!",
	"Foot-crafted?",
	"Crafted with some organic appendages!",
	"Spatial!",
	"CaSe-O-mAtIc!",
	"cAsE-o-MaTiC!",
	"Monochromatic!",
	"Platform-independent!",
	"Made in LӦVE!",
	"Obey!",
	"Open source!",
	"Libre!",
	"So therefore...",
	"Deeply complexed!",
	"Freud would have a field day with it!",
	"Peachy!",
	"Metric!",
	"Edmund Mahon!",
	"Killerbites of datums!",
	"Kilobytes of data!",
	"Covered in bacteria!",
	"Speaks Latin!",
	"Doesn't know where Greece is!",
	"Hates people who hate!",
	"Recycles!",
	"Is poorly coded!",
	"Thinks about carrots!",
	"Fizzy!",
	"Is not very businessy!",
	"makes the rockin' world go round!",
	"Is the real life!",
	"Is just fantasy!",
	"Breaks fundamental axioms of algebra!",
	"Fixes fundamental axioms of algebra!",
	"Dislikes hEAlthcare as seen in America!",
	"Won't let EA near it!",
	"Eulaworld has nothing to do with terms and conditions!",
	"Loves grandma's gnocci!",
	"Won't recommend Cacodemon back sprites!",
	"Topological!",
	"Menstrual, innit!",
	"Elementary!",
	"Alimentary...?",
	"Likes ya t'be complimennary, innit!",
	"Has a shelf dedicated to storing shelves!",
	"Comes before 1 and after 2!",
	"Swallows!",
	"Has at least one inappropriate title variant!",
	"Spits!",
	"Is pointless!",
	"Is pointy!",
	"Can't say holline mami! ...Holtine mimi? ...Yeah!",
	"Hold tight Harrybo!",
	"The Skyfoogle's best friend!",
	"CLONG!!",
	"Soochy.",
	"-100% feature-redisinprocompletionising!",
	"Always tries to start something!",
	"Boin chest best chest!",
	"Oh, there's another one!",
	"Ridiculous!",
	"Reddickcoolasslee fun!",
	"International phonetic alphabet!",
	"Inspired by Nihon Kenchiku!",
	"owo",
	"uwu",
	"Wears 2-metre thick spectacles!",
	"Ate the sun!",
	"Online (Bot)",
	"Is an unholy fusion of flesh and metal!",
	"Isn't a holy fission of bone and wood!",
	"Cyberdemonic!",
	"SCREAMING JESUS!!!",
	"Deciduous!",
	"Coniferous!",
	"Fishy...",
	"doesnt type on a phone at all",
	"Eh, reddit already!",
	"Okay, this is epic!",
	"Now this... this is epic!!",
	"I've never seen anything like this! It's just... it's just... EPIC!!!",
	"Stop! Don't shoot!",
	"Well, this is awkward!",
	"Is all ears.",
	"POP!",
	"Drop him!",
	"BANG BANG BANG!",
	"Don't come any closer, or we'll shoot!",
	"YouLCD!",
	"MySpacetime!",
	"Tumbler!",
	"HECC",
	"Is searching for an larvae, or is searching for self?",
	"self == epic",
	"George Boole xnors while he sleeps!",
	"nxor > xnor",
	"Crocodile mnemonics!",
	"Oh Be A Fine Girl Kiss Me!",
	"Oh Batter A Fly! Get Killing, Missy!",
	"Only Boring Astronomers Find Gratification Knowing Mnemonics!",
	"Beep-beep!",
	"Has been trained to use the light!",
	"Is a robot!",
	"We are the robots!",
	"Likes Kraftwerk!",
	"Craftwork?",
	"Man Machine!",
	"Woman Organ?",
	"Join the pile!",
	"BEE!",
	"Is stuck in Babylon!",
	"Inconceivable, yet believeable!",
	"Shot that monkey, two times!",	
	"Puts the crap on the stick!",
	"Trained in Bar-Fu!",
	"Catchphrase.",
	"Orihime!",
	"Hapens to b a blakc belte in cerarti!",
	"Saved by the bell!",
	"Attacked by the braben?",
	"Incorrectly advertised!",
	"Try Steam Proton!",
	"Fish juice!",
	"prins fillip and kween victorier",
	"Is still hunting the unholy trinity!",
	"Crackpot's crazy music!",
	"Ding dong!",
	"Rob the value of the bartered product from the cashier and leave without the product!",
	"Economic!",
	"Economical?",
	"Radical!",
	"Has rad art!",
	"Wears christmas jumpers!",
	"Is doe-eyed!",
	"Neurotypical screeching!",
	"A master of the American Spy Squat!",
	"Armoured pizza carriers!",
	"Is a master of the butterfly effect!",
	"Everything in existence except for your foot puts your sock on!",
	"It means it's living!",
	"YOU'RE LIVING!",
	"chronos - money = 0",
	"L-Lua San~",
	":thinking:",
	"colon bee colon",
	"Is matte!",
	"Davidek Arrowie!",
	"Farms sooch!",
	"Plates made of stale bread!",
	"Randomly said chainsaw!",
	"A total champloo!",
	"Lagnographic!",
	"Romantic!",
	"Romantical?",
	"Moving images in newspaper articles would use CMY for each pixel!",
	"arr gee bee aey leits on monniters",
	"print)\"Bye, world!\"(",
	"love.[\"graphics\"][\"draw\"](drawable and drawable or nil)",
	"Let's make angry oranges!",
	"Raid Oliver's flippin' larder!",
	"Grandddddddddad!",
	"RIP in peace?",
	"PIN number?",
	"SMH my head!",
	"Almost last!",
	"Seeing all of these ruins the fun!"
}
